/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpsLbCliDevConfigSchemaJson {
  /**
   * Default Linear team key (e.g., 'LIN'). Used when no team is specified in commands.
   */
  team_key?: string;
  /**
   * Name used for repo: label in Linear. Overrides auto-detection from git remote or directory name.
   */
  repo_name?: string;
  /**
   * Enable issue type labels (Bug, Feature, Task, etc.) using Linear label groups. When false, types are not tracked.
   */
  use_issue_types?: boolean;
  /**
   * How long to trust cached data before re-syncing from Linear, in seconds.
   */
  cache_ttl_seconds?: number;
  /**
   * Run in local-only mode without syncing to Linear. Issues get LOCAL-xxx IDs. Useful for LLM-only task tracking.
   */
  local_only?: boolean;
  /**
   * How to scope issues to this repo in Linear. 'label' uses repo:name labels. 'project' uses Linear Projects. 'both' uses both for filtering/assignment. When omitted, repo_binding_version controls the implicit fallback.
   */
  repo_scope?: "label" | "project" | "both";
  /**
   * Binding policy version for implicit repo scope fallback when repo_scope is not explicitly set. Version 1 defaults to label scope, version 2 defaults to project scope.
   */
  repo_binding_version?: 1 | 2;
  /**
   * Minimum lb CLI version required for this repository (for example: 'v16'). Older binaries exit early with an upgrade message.
   */
  min_cli_version?: string;
  /**
   * Issue backend adapter. 'linear' uses Linear GraphQL. 'local' keeps issue operations local-only.
   */
  issue_backend?: "linear" | "local";
  /**
   * Mail backend adapter. 'local' keeps mail in local SQLite. 'linear' projects mail through Linear comments.
   */
  mail_backend?: "local" | "linear";
}
